### ISSUE TITLE
论文疑问

### ISSUE THREAD

**Issue by Delete12137** [cosinehuang/HESP#1]
你好，非常感谢你们的工作！
我在阅读论文时发现数字有误，如下图：
![image](https://github.com/user-attachments/assets/9fb62c88-6e6b-43e2-9bad-cca91cb538c1)
请问是不是应该为O(7：4)?

**Comment by cosinehuang** [comment]
感谢你的指出！确实是我们的疏忽，这里写错了，应该是O(7:4)=0.20.

**Comment by cosinehuang** [comment]
感谢你的指出！确实是我们的疏忽，这里写错了，应该是O(7:4)=0.20.
