### ISSUE TITLE
Video-based FER和Dynamic FER的区别

### ISSUE THREAD

**Issue by Delete12137** [cosinehuang/HESP#3]
你好，我最近在调研video-based FER工作时发现还有很多Dynamic FER，我想请问一下这两个任务有什么区别吗？因为我发现你文章中使用的MAFW的主页介绍写着“MAFW is a large-scale, multi-modal, compound affective database for dynamic facial expression recognition in the wild”。并且从输入输出上看，似乎两者都是输入一段视频序列，输出表情的类别标签？
最近才开始接触到相关任务，很多概念还不是很清晰，如果能得到你的解答，不甚感激！

**Comment by cosinehuang** [comment]
感谢你的提问。在我看来，video-based FER和Dynamic FER广义上其实是相同的任务，输入都是一段视频序列，但在细节和侧重点上存在一些区别。video-based FER更广泛，涵盖了从视频中提取和识别表情的所有过程，利用视频的时序信息提高识别效果。Dynamic FER更专注于分析表情变化的动态过程，强调对时间维度上变化模式的建模和理解。
在一些研究中为video-based FER划分了两种方法，一种是frame-based method，另一种是dynamic sequence-based method（可以参考我们团队的另外两篇论文1.“Clip-aware expressive feature learning for video-based facial expression recognition”，2.“Expression snippet transformer for robust video-based facial expression recognition”），由此看来其实Dynamic FER是包含在video-based FER内的。
希望我的回答对你有所帮助。

**Comment by Delete12137** [comment]
非常感谢！
