### ISSUE TITLE
MAFW数据集

### ISSUE THREAD

**Issue by Delete12137** [cosinehuang/HESP#4]
你好，我已经按照MAFW数据集官方网站的要求于上周四进行了申请，但是一直没有收到回复。我发现MAFW数据集的作者和您都是同一个学校的，请问您能否帮我咨询一下相关进度？大概什么时候可以获得审批？非常感谢！

**Comment by cosinehuang** [comment]
你好，该数据集的负责人最近有些忙，我已经告知她你的申请。另外，你需要确保你申请的资料都填写完整，包括姓名机构等信息。如果申请材料完整且没有问题，她这两天会尽快处理。

**Comment by cosinehuang** [comment]
如果你方便告知你申请时所填写的姓名，应该可以更快给你审批答复

**Comment by Delete12137** [comment]
好的，非常感谢我已经收到他的回复。发自我的 iPhone在 2024年9月4日，11:00，cosinehuang ***@***.***> 写道：﻿
你好，该数据集的负责人最近有些忙，我已经告知她你的申请。另外，你需要确保你申请的资料都填写完整，包括姓名机构等信息。如果申请材料完整且没有问题，她这两天会尽快处理。
